services:

  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-16-bullseye
    network_mode: service:postgres
    environment:
      PGUSER: dev
      PGPASSWORD: dev
      PGDATABASE: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    command: sleep infinity

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgweb:
    image: sosedoff/pgweb:0.11.11
    network_mode: service:postgres
    environment:
      - DATABASE_URL=postgres://dev:dev@localhost/dev?sslmode=disable
    depends_on:
      - postgres
    restart: always

volumes:

  home_dev:
  postgres_data:
