version: '3.7'

services:

  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-16-bullseye
    environment:
      PGHOST: postgres
      PGUSER: dev
      PGPASSWORD: dev
      PGDATABASE: dev
    volumes:
      - home_dev:/home/dev
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:0.11.11
    environment:
      - DATABASE_URL=postgres://dev:dev@postgres/dev?sslmode=disable
    ports:
      - 8081:8081
    depends_on:
      - postgres
    restart: always

volumes:

  home_dev:
  postgres_data:
